<?php

namespace Enmaboya\PlaceInput\Traits;

trait CountryTrait
{
    private function getCountriesListWithContinent()
    {
        return [
            'AF' => [
                "AO" => __('Angola'),
                "BJ" => __('Benin'),
                "BW" => __('Botswana'),
                "BF" => __('Burkina Faso'),
                "BI" => __('Burundi'),
                "CM" => __('Cameroon'),
                "CF" => __('Central African Republic'),
                "TD" => __('Chad'),
                "KM" => __('Comoros'),
                "DJ" => __('Djibouti'),
                "EG" => __('Egypt'),
                "GQ" => __('Equatorial Guinea'),
                "ET" => __('Ethiopia'),
                "GA" => __('Gabon'),
                "GM" => __('Gambia'),
                "GH" => __('Ghana'),
                "GN" => __('Guinea'),
                "GW" => __('Guinea-Bissau'),
                "KE" => __('Kenya'),
                "LS" => __('Lesotho'),
                "LR" => __('Liberia'),
                "LY" => __('Libya'),
                "MG" => __('Madagascar'),
                "MW" => __('Malawi'),
                "ML" => __('Mali'),
                "MR" => __('Mauritania'),
                "MU" => __('Mauritius'),
                "MA" => __('Morocco'),
                "MZ" => __('Mozambique'),
                "NA" => __('Namibia'),
                "NE" => __('Niger'),
                "NG" => __('Nigeria'),
                "RW" => __('Rwanda'),
                "ST" => __('Sao Tome and Principe'),
                "SN" => __('Senegal'),
                "SC" => __('Seychelles'),
                "SL" => __('Sierra Leone'),
                "SO" => __('Somalia'),
                "ZA" => __('South Africa'),
                "SS" => __('South Sudan'),
                "SD" => __('Sudan'),
                "TZ" => __('Tanzania'),
                "TG" => __('Togo'),
                "TN" => __('Tunisia'),
                "UG" => __('Uganda'),
                "ZM" => __('Zambia'),
                "ZW" => __('Zimbabwe'),
            ],

            'AS' => [
                "AF" => __('Afghanistan'),
                "AM" => __('Armenia'),
                "AZ" => __('Azerbaijan'),
                "BH" => __('Bahrain'),
                "BD" => __('Bangladesh'),
                "BT" => __('Bhutan'),
                "KH" => __('Cambodia'),
                "CN" => __('China'),
                "CY" => __('Cyprus'),
                "GE" => __('Georgia'),
                "IN" => __('India'),
                "ID" => __('Indonesia'),
                "IQ" => __('Iraq'),
                "IL" => __('Israel'),
                "JP" => __('Japan'),
                "JO" => __('Jordan'),
                "KZ" => __('Kazakhstan'),
                "KW" => __('Kuwait'),
                "KG" => __('Kyrgyzstan'),
                "LB" => __('Lebanon'),
                "MY" => __('Malaysia'),
                "MV" => __('Maldives'),
                "MN" => __('Mongolia'),
                "NP" => __('Nepal'),
                "OM" => __('Oman'),
                "PK" => __('Pakistan'),
                "PH" => __('Philippines'),
                "QA" => __('Qatar'),
                "SA" => __('Saudi Arabia'),
                "SG" => __('Singapore'),
                "LK" => __('Sri Lanka'),
                "TW" => __('Taiwan'),
                "TJ" => __('Tajikistan'),
                "TH" => __('Thailand'),
                "TL" => __('Timor-Leste'),
                "TR" => __('Turkey'),
                "TM" => __('Turkmenistan'),
                "AE" => __('United Arab Emirates'),
                "UZ" => __('Uzbekistan'),
                "VN" => __('Vietnam'),
                "YE" => __('Yemen'),
            ],

            'EU' => [
                "AL" => __('Albania'),
                "AD" => __('Andorra'),
                "AM" => __('Armenia'),
                "AT" => __('Austria'),
                "AZ" => __('Azerbaijan'),
                "BY" => __('Belarus'),
                "BE" => __('Belgium'),
                "BA" => __('Bosnia and Herzegovina'),
                "BG" => __('Bulgaria'),
                "HR" => __('Croatia'),
                "CY" => __('Cyprus'),
                "DK" => __('Denmark'),
                "EE" => __('Estonia'),
                "FI" => __('Finland'),
                "FR" => __('France'),
                "GE" => __('Georgia'),
                "DE" => __('Germany'),
                "GR" => __('Greece'),
                "HU" => __('Hungary'),
                "IS" => __('Iceland'),
                "IE" => __('Ireland'),
                "IT" => __('Italy'),
                "KZ" => __('Kazakhstan'),
                "XK" => __('Kosovo'),
                "LV" => __('Latvia'),
                "LI" => __('Liechtenstein'),
                "LT" => __('Lithuania'),
                "LU" => __('Luxembourg'),
                "MT" => __('Malta'),
                "MD" => __('Moldova'),
                "MC" => __('Monaco'),
                "ME" => __('Montenegro'),
                "NL" => __('Netherlands'),
                "NO" => __('Norway'),
                "PL" => __('Poland'),
                "PT" => __('Portugal'),
                "RO" => __('Romania'),
                "SM" => __('San Marino'),
                "RS" => __('Serbia'),
                "SK" => __('Slovakia'),
                "SI" => __('Slovenia'),
                "ES" => __('Spain'),
                "SE" => __('Sweden'),
                "CH" => __('Switzerland'),
                "TR" => __('Turkey'),
                "UA" => __('Ukraine'),
                "GB" => __('United Kingdom'),
            ],

            'NA' => [
                "AG" => __('Antigua and Barbuda'),
                "BS" => __('Bahamas'),
                "BB" => __('Barbados'),
                "BZ" => __('Belize'),
                "CA" => __('Canada'),
                "CR" => __('Costa Rica'),
                "CU" => __('Cuba'),
                "DM" => __('Dominica'),
                "DO" => __('Dominican Republic'),
                "SV" => __('El Salvador'),
                "GD" => __('Grenada'),
                "GT" => __('Guatemala'),
                "HT" => __('Haiti'),
                "HN" => __('Honduras'),
                "JM" => __('Jamaica'),
                "MX" => __('Mexico'),
                "NI" => __('Nicaragua'),
                "PA" => __('Panama'),
                "KN" => __('Saint Kitts and Nevis'),
                "LC" => __('Saint Lucia'),
                "TT" => __('Trinidad and Tobago'),
                "US" => __('United States of America'),
            ],

            'OC' => [
                "AU" => __('Australia'),
                "FJ" => __('Fiji'),
                "KI" => __('Kiribati'),
                "MH" => __('Marshall Islands'),
                "NR" => __('Nauru'),
                "NZ" => __('New Zealand'),
                "PW" => __('Palau'),
                "PG" => __('Papua New Guinea'),
                "WS" => __('Samoa'),
                "SB" => __('Solomon Islands'),
                "TO" => __('Tonga'),
                "TV" => __('Tuvalu'),
                "VU" => __('Vanuatu'),
            ],

            'SA' => [
                "AR" => __('Argentina'),
                "BO" => __('Bolivia'),
                "BR" => __('Brazil'),
                "CL" => __('Chile'),
                "CO" => __('Colombia'),
                "EC" => __('Ecuador'),
                "GY" => __('Guyana'),
                "PY" => __('Paraguay'),
                "PE" => __('Peru'),
                "SR" => __('Suriname'),
                "UY" => __('Uruguay'),
                "VE" => __('Venezuela'),
            ]
        ];
    }

    private function getCountriesByContinent(array $continents)
    {
        return collect($this->getCountriesListWithContinent())->filter(function ($countries, $continent) use ($continents) {
            if (in_array($continent, $continents)) {
                return $countries;
            }
        })->collapse()->keys()->toArray();
    }
}
